nmHoistingLimits: dependencies

nodeLinker: node-modules

packageExtensions:
  "@vue/cli-plugin-typescript@*":
    dependencies:
      "@babel/core": "*"
      babel-loader: "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-eslint": ^4
      "@vue/cli-plugin-typescript": ^4
      "@vue/cli-plugin-unit-jest": ^4
      vue-template-compiler: ^2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
